### ISSUE TITLE
Not Available

### ISSUE THREAD

**Issue by iamrahul10** [JasonD94/android-hosts#2]
The status is showing as local: not available online: not available

**Comment by JasonD94** [comment]
I have no idea what this error message is for. I assume you're trying to include these hosts with an ad blocking app like AdAway. As I mentioned in another issue, there's a known issue using AdAway with raw.githubusercontent.com links. You can feel free to complain to AdAway if that's the app you're using, try another app like [DNS66](https://github.com/julian-klode/dns66), or download the file and manually import it into AdAway. Or feel free to download the hosts file and host it somewhere else that AdAway can read from.

[More information on the previous issue here.](https://github.com/JasonD94/android-hosts/issues/1)

**Comment by iamrahul10** [comment]
Thanks for the info.
Yes, I am using AdAway.
So I will contact them.

And thank for you for the hosts.


Rahul Nambiampurath
PPC | SMM | CRO | ORM
w: ir10.in    e:  i@ir10.in
<https://www.google.com/partners/?hl=en-GB#i_profile;idtf=101475480249078125219;>

<https://www.google.com/partners/?hl=en-GB#i_profile;idtf=101475480249078125219;>

<https://www.google.com/partners/?hl=en-GB#i_profile;idtf=101475480249078125219;>

<https://www.google.com/partners/?hl=en-GB#i_profile;idtf=101475480249078125219;>
[image: Contact]
<https://advertise.bingads.microsoft.com/en-us/training-accreditation-directory/pro/id/60080/rahul-nambiampurath>
